coreofscience/tos.coreofscience.org

src/components/upload/FileDiv.tsx, src/components/upload/UploadIndicator.tsx
=> New file div

public/index.html, src/components/upload/FileCard.css, src/components/upload/FileCard.tsx, src/components/upload/FileDiv.tsx, src/components/upload/FileDropper.css, src/components/upload/FileDropper.tsx, src/components/upload/Home.css, src/components/upload/Home.tsx, src/components/upload/UploadIndicator.tsx, src/components/vectors/CancelFile.tsx
this is the css the principal page
=> Css principal.page

src/App.tsx, src/components/layout/AppLayout.css, src/components/layout/AppLayout.tsx, src/components/layout/Footer.css, src/components/layout/Footer.tsx, src/components/layout/Header.css, src/components/layout/Header.tsx, src/components/providers/FilesProvider.tsx, src/components/tree/Tree.tsx, src/components/upload/FileCard.tsx, src/components/upload/FileDropper.tsx, src/components/upload/Home.css, src/components/upload/Home.tsx, src/components/upload/UploadIndicator.tsx, src/context/files.tsx, src/index.css, src/utils/counter.tsx, src/utils/customTypes.tsx, tsconfig.json
- Refactor the app layout
- Fix rogue button
- Tarea para juan
- Fix some typos
- Get front page formated
=> file store context

.github/workflows/deploy-dev-site.yml, .github/workflows/deploy-preview.yml, .gitignore, firebase.json, src/App.tsx, src/components/layout/Header.tsx, src/components/providers/FirebaseProvider.tsx, src/components/tree/Result.tsx, src/components/tree/Tree.tsx, src/components/upload/Home.tsx
=> Load those trees from results

.github/workflows/deploy-dev-site.yml, .github/workflows/deploy-preview.yml, .gitignore, firebase.json, src/App.tsx, src/components/layout/Header.tsx, src/components/providers/FirebaseProvider.tsx, src/components/tree/Result.tsx, src/components/tree/Tree.tsx, src/components/upload/Home.tsx
Reverts coreofscience/sap.coreofscience.com#30
=> Revert "Revert "Load those trees from results""

.gitignore, src/hooks/useUpload.ts
closes https://github.com/coreofscience/sap.coreofscience.com/issues/14
=> Do not upload files if they exists on firebase storage

src/components/upload/FileDropper.tsx, src/components/upload/FileErrors.tsx, src/components/upload/errors.ts, src/hooks/useError.ts, src/utils/customTypes.tsx, src/utils/isiUtils.tsx
closes https://github.com/coreofscience/sap.coreofscience.com/issues/35
=> Reject big files

src/components/layout/AppLayout.css, src/components/layout/Footer.css, src/components/layout/Footer.tsx, src/components/tree/Reference.tsx
closes https://github.com/coreofscience/sap.coreofscience.com/issues/13
=> Add the ToS citation articles in the footer

src/components/NotFound.tsx, src/components/layout/Footer.tsx, src/components/tree/Reference.tsx, src/react-app-env.d.ts, src/serviceWorker.ts, src/setupTests.ts
- add new article to the footer
- add new article to the footer firt
- new chenges to the article
- remove dot automatic
=> New article in cos

.firebaserc, .gitignore, firebase.json, functions/.gitignore, functions/main.py, functions/requirements.txt, storage.rules
- Add the function configuration to process an user tree
- Firebase rules have been updated already
=> Add functions configuration

README.md, firebase.json, package.json, src/context/FirebaseContext.tsx, src/env.d.ts
=> Add emulators workflow

src/components/account/SignUp/hooks/useSignUp/index.ts, src/components/common/Toast/constants/index.ts, src/components/common/Toast/hideToast.ts, src/components/common/Toast/index.tsx, src/components/common/Toast/showToast.tsx, src/components/common/Toast/styles.css, src/context/FileContext.tsx, src/types/fileContextType.ts, src/types/toastType.ts
The following fixes were made:
- Renamed the interface from `FileContexType` to `FileContextType`.
Added the following components in `src/components/common`:
- Toast: to show notifications to users after an action.
Also added **Firebase** method `sendEmailVerification` to send a verification email when the user is successfully registered.
=> Send verification email #66

functions/main.py, src/components/tree/Tree.css, src/components/tree/Tree.tsx, src/components/tree/constants/info.ts, src/index.css, src/types/article.ts, src/types/treeType.ts
Three buttons were added to the **Tree** component, which are:
- Branch Type 1
- Branch Type 2 
-  Branch Type 3
Where each one is responsible for displaying the **articles** and **keywords** that belong to each type of **branch**.
Preview of how the buttons would look like:
=> Add branches to the tree

functions/main.py
Create a new function which will have more memory capacity and megabytes, since it is for the `proTrees`, this function will have as activator `document="users/{userId}/proTrees/{proTreeId}"`.
- memory=MemoryOption.MB_1024,
- max_size_megabytes=100
=> Create new function for proTrees

functions/main.py, src/App.tsx, src/components/providers/UserProvider.tsx, src/components/tree/Result.tsx, src/components/upload/Home/createTree.ts, src/components/upload/Home/index.tsx, src/components/upload/TreeHistory/index.tsx, src/types/userContextType.ts
The following modifications were made for the preparation of the Pro Trees:
- Updated the UI to allow uploading files up to **100 megabyte** if the user has the **pro** plan.
- Updated the `createTreee` to create `proTrees`.
- Updated the `Result` component to work with the `proTrees`
- Created a new path for the `proTrees` .
=> Preparation for the pro trees

functions/main.py
A new function has been added, which is executed every hour (schedule trigger). This function queries the **plans** collection and evaluates if the registered **users** are added to the **pro** or **free** plan.
=> Add function to add custom claims for the plan

package-lock.json, package.json, src/App.tsx, src/components/common/TableOfContent/constants/index.ts, src/components/common/TableOfContent/index.tsx, src/components/pages/docs/Sap.tsx, src/components/tree/Tree.tsx, src/components/tree/constants/info.ts, src/types/tableOfContent.ts, src/types/treeType.ts, tailwind.config.js
Added page for documentation. The path to the page is `/docs/sap`.
=> Add SAP page for docs

src/components/pages/Home/TrustUs.tsx, src/components/pages/Home/index.tsx, src/components/upload/FileDropper/index.tsx, src/components/upload/TOS/index.tsx, src/utils/getMaxSize.ts
Added an input for users to add files from the home page and redirect them to `/tos`.
=> Add file dropper to home page

src/App.tsx, src/components/layout/Footer.tsx, src/components/pages/docs/About.tsx, src/components/pages/docs/FAQ.tsx, src/components/pages/docs/Sap.tsx
- Give sap and faq a once do over
- Add the about page
- Scroll up
=> add about page

.github/workflows/deploy-dev-site.yml, .github/workflows/deploy-preview.yml, .github/workflows/deploy-prod-site.yml, .nvmrc, src/components/tree/Result.tsx, src/components/upload/TOS/index.tsx
=> Upgrade node version

src/App.tsx, src/components/layout/Footer.tsx, src/components/pages/docs/About.tsx, src/components/pages/docs/PressRelease.tsx, src/components/pages/docs/Sap.tsx
=> Add press release

src/App.tsx, src/components/tree/Reference.tsx, src/components/tree/Tree.tsx, src/components/upload/Tos/New.tsx, src/components/upload/Tos/createTree.ts, src/components/upload/Tos/index.tsx, src/types/article.ts
=> Add openalex search

src/components/upload/Tos/New.tsx, src/components/upload/TreeHistory/hooks/useTrees.ts, src/components/upload/TreeHistory/index.tsx
=> Fix tree history

functions/main.py, functions/requirements.txt, package-lock.json, src/components/ui/Button.tsx, src/components/upload/FileDropper.tsx, src/utils/metadata.ts, src/utils/scopusCsv.ts, src/utils/scopusRis.ts
- **Add new version of bibx**
- **Add support for scopus CSV**
=> add scopus csv support
